function pars = InitGMOS_Col(d)
ds                      = 5e-5; % initial step size
dsMax                   = 1e-1; % max step size
dsMin                   = 3e-5; % min step size
Iter                    = 10; % max Newton iters
Ntrial                  = 4; % # attempts to find torus
M                       = 51; % time nodes (how many strob maps to store)
N                       = 41; % number of points in strob map
Nmax                    = 42; % number of QPOs
Opt                     = 5; % optimal no. iters
Plt                     = 1; % plotting flag (0,1)
txt                     = 0; % text flag (0,1)
stab                    = 0; % compute stability info flag (0,1)
pc                      = 1; % parameterization constraint flag (1,2,3)
Tol                     = 1e-10; % convergence tolerance
m                       = 7; % number of collocation points in each interval
n                       = 51; % number of mesh intervals
[DFT,IDFT,DT] = DFTv3(d,N);

pars.GMOS.ds            = ds;
pars.GMOS.dsMax         = dsMax;
pars.GMOS.dsMin         = dsMin;
pars.GMOS.Iter          = Iter;
pars.GMOS.Ntrial        = Ntrial;
pars.GMOS.M             = M;
pars.GMOS.N             = N;
pars.GMOS.Nmax          = Nmax;
pars.GMOS.Opt           = Opt;
pars.GMOS.Plt           = Plt;
pars.GMOS.Tol           = Tol;
pars.GMOS.txt           = txt;
pars.GMOS.param_const   = pc;
pars.GMOS.stab          = stab;
pars.GMOS.DFT           = DFT;
pars.GMOS.IDFT          = IDFT;
pars.GMOS.DT            = DT{1};
pars.GMOS.Collocation.m = m;
pars.GMOS.Collocation.n = n;
end